import AVFoundation
import Speech

/// A tiny handoff between the barge-in recognizer that runs while Jarvis is
/// speaking and the normal command recognizer that starts immediately after
/// speech stops. Keeping the prefix lets a sentence begun over Jarvis's voice
/// continue naturally once Jarvis has yielded the audio channel.
@MainActor
enum BargeInBuffer {
    private static var pendingText = ""

    static func store(_ text: String) {
        pendingText = text.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    static func take() -> String {
        let value = pendingText
        pendingText = ""
        return value
    }
}

@MainActor
final class SpeechSynthesizer: NSObject, ObservableObject, AVSpeechSynthesizerDelegate, AVAudioPlayerDelegate {
    @Published private(set) var isSpeaking = false

    private let synthesizer = AVSpeechSynthesizer()
    private let audioRouteManager: AudioRouteManager
    private var audioPlayer: AVAudioPlayer?
    private var completion: CheckedContinuation<Void, Never>?
    private var currentUtterance: AVSpeechUtterance?

    // A second, short-lived recognition pipeline is active only while Jarvis is
    // talking. It works for both Apple-TTS fallback audio and Qwen-generated WAVs,
    // so the wearer can interrupt either path naturally.
    private let bargeInRecognizer = SFSpeechRecognizer(locale: Locale(identifier: "en-US"))
    private let bargeInAudioEngine = AVAudioEngine()
    private var bargeInRequest: SFSpeechAudioBufferRecognitionRequest?
    private var bargeInTask: SFSpeechRecognitionTask?
    private var bargeInTapInstalled = false
    private var bargeInFinalizeTask: Task<Void, Never>?
    private var spokenTextForEchoFilter = ""
    private var latestBargeInTranscript = ""
    private var lastBargeInTranscriptChange = Date.distantPast
    private var didBargeIn = false

    init(audioRouteManager: AudioRouteManager) {
        self.audioRouteManager = audioRouteManager
        super.init()
        synthesizer.delegate = self
    }

    /// Apple speech remains a fallback for times when the PC-side Qwen TTS model
    /// is starting, unavailable, or the phone has lost its route to the PC.
    func speak(_ text: String, preferBluetooth: Bool) async {
        let cleaned = Self.respectfulSpeechText(
            text.trimmingCharacters(in: .whitespacesAndNewlines)
        )
        guard !cleaned.isEmpty else { return }

        stopSpeaking()
        prepareOutput(text: cleaned, preferBluetooth: preferBluetooth)

        let utterance = AVSpeechUtterance(string: cleaned)
        utterance.voice = preferredJarvisVoice()
        utterance.rate = 0.50
        utterance.pitchMultiplier = 1.0
        utterance.volume = 0.90
        utterance.preUtteranceDelay = 0.02
        utterance.postUtteranceDelay = 0.02
        currentUtterance = utterance

        await withCheckedContinuation { continuation in
            completion = continuation
            synthesizer.speak(utterance)
            startBargeInListening()
        }
    }

    /// Plays a WAV generated by the local Qwen3-TTS service. This is the normal
    /// Jarvis voice path. Barge-in uses the same full-duplex microphone and echo
    /// filter as the Apple fallback, so moving TTS to the PC does not regress
    /// conversational interruption.
    func speakRemoteAudio(
        _ data: Data,
        text: String,
        preferBluetooth: Bool
    ) async throws {
        let cleaned = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !cleaned.isEmpty else { return }

        stopSpeaking()
        prepareOutput(text: cleaned, preferBluetooth: preferBluetooth)

        let player = try AVAudioPlayer(data: data)
        player.delegate = self
        player.prepareToPlay()
        audioPlayer = player

        await withCheckedContinuation { continuation in
            completion = continuation
            if player.play() {
                startBargeInListening()
            } else {
                finalizeCurrentOutput()
            }
        }
    }

    private func prepareOutput(text: String, preferBluetooth: Bool) {
        do {
            try audioRouteManager.prepareForVoice(preferBluetooth: preferBluetooth)
        } catch {
            // Playback can still succeed on the current route. Route setup errors
            // should not suppress Jarvis's response.
        }
        isSpeaking = true
        spokenTextForEchoFilter = text
        latestBargeInTranscript = ""
        lastBargeInTranscriptChange = Date.distantPast
        didBargeIn = false
        BargeInBuffer.store("")
    }

    private static func respectfulSpeechText(_ text: String) -> String {
        guard !text.isEmpty else { return text }
        if text.range(of: "sir", options: [.caseInsensitive, .diacriticInsensitive]) != nil {
            return text
        }
        if text == "Yes?" {
            return "Yes, sir?"
        }
        if text == "Ready. Say confirm or cancel." {
            return "Ready, sir. Say confirm or cancel."
        }
        return "Sir, " + text.prefix(1).lowercased() + String(text.dropFirst())
    }

    private func preferredJarvisVoice() -> AVSpeechSynthesisVoice? {
        let voices = AVSpeechSynthesisVoice.speechVoices()
        let usEnglish = voices.filter { $0.language.lowercased().hasPrefix("en-us") }
        let preferredNames = ["Alex", "Ava", "Samantha", "Nathan", "Evan", "Tom"]
        for name in preferredNames {
            let matches = usEnglish.filter {
                $0.name.compare(name, options: [.caseInsensitive, .diacriticInsensitive]) == .orderedSame
            }
            if let best = matches.max(by: { $0.quality.rawValue < $1.quality.rawValue }) {
                return best
            }
        }
        return AVSpeechSynthesisVoice(language: "en-US")
    }

    func stopSpeaking() {
        guard currentUtterance != nil || audioPlayer != nil || isSpeaking else { return }
        bargeInFinalizeTask?.cancel()
        bargeInFinalizeTask = nil
        didBargeIn = false
        if synthesizer.isSpeaking {
            synthesizer.stopSpeaking(at: .immediate)
        }
        if audioPlayer?.isPlaying == true {
            audioPlayer?.stop()
        }
        finalizeCurrentOutput()
    }

    private func startBargeInListening() {
        guard SFSpeechRecognizer.authorizationStatus() == .authorized,
              let bargeInRecognizer,
              bargeInRecognizer.isAvailable else {
            return
        }

        stopBargeInListening()

        let request = SFSpeechAudioBufferRecognitionRequest()
        request.shouldReportPartialResults = true
        request.taskHint = .dictation
        request.contextualStrings = ["Jarvis", "stop", "wait", "hold on", "actually", "Dubeck"]
        if bargeInRecognizer.supportsOnDeviceRecognition {
            request.requiresOnDeviceRecognition = true
        }
        bargeInRequest = request

        let input = bargeInAudioEngine.inputNode
        let format = input.outputFormat(forBus: 0)
        guard format.sampleRate > 0, format.channelCount > 0 else {
            bargeInRequest = nil
            return
        }

        input.installTap(onBus: 0, bufferSize: 1024, format: format) { buffer, _ in
            request.append(buffer)
        }
        bargeInTapInstalled = true

        bargeInAudioEngine.prepare()
        do {
            try bargeInAudioEngine.start()
        } catch {
            stopBargeInListening()
            return
        }

        bargeInTask = bargeInRecognizer.recognitionTask(with: request) { [weak self] result, _ in
            Task { @MainActor in
                guard let self, self.isSpeaking, let result else { return }
                let heard = result.bestTranscription.formattedString
                    .trimmingCharacters(in: .whitespacesAndNewlines)
                guard !heard.isEmpty else { return }

                if heard != self.latestBargeInTranscript {
                    self.latestBargeInTranscript = heard
                    self.lastBargeInTranscriptChange = Date()
                }

                if self.didBargeIn {
                    BargeInBuffer.store(self.commandPayload(fromInterruption: heard))
                    return
                }

                guard self.shouldBargeIn(with: heard) else { return }
                self.didBargeIn = true
                BargeInBuffer.store(self.commandPayload(fromInterruption: heard))

                // Stop only the audio output. Keep this microphone alive until the
                // user's interruption reaches a pause so the handoff contains the
                // whole sentence rather than merely its first word.
                if self.synthesizer.isSpeaking {
                    self.synthesizer.stopSpeaking(at: .immediate)
                }
                if self.audioPlayer?.isPlaying == true {
                    self.audioPlayer?.stop()
                    self.beginBargeInFinalize()
                }
            }
        }
    }

    private func shouldBargeIn(with heard: String) -> Bool {
        let normalizedHeard = Self.normalizedWords(heard)
        guard !normalizedHeard.isEmpty else { return false }
        if isLikelyEcho(heard) { return false }

        let joined = normalizedHeard.joined(separator: " ")
        let explicit = [
            "jarvis", "stop", "wait", "hold on", "actually", "no",
            "but", "what", "why", "how", "when", "where", "who",
            "which", "can you", "could you", "don't", "do not"
        ]
        if explicit.contains(where: { cue in
            joined == cue || joined.hasPrefix(cue + " ")
        }) {
            return true
        }
        return normalizedHeard.count >= 2
    }

    private func isLikelyEcho(_ heard: String) -> Bool {
        let heardWords = Self.normalizedWords(heard)
        let spokenWords = Self.normalizedWords(spokenTextForEchoFilter)
        guard !heardWords.isEmpty, !spokenWords.isEmpty else { return false }

        let heardString = heardWords.joined(separator: " ")
        let spokenString = spokenWords.joined(separator: " ")
        if spokenString.contains(heardString) { return true }

        let spokenSet = Set(spokenWords)
        let overlap = heardWords.filter { spokenSet.contains($0) }.count
        return heardWords.count >= 2 && Double(overlap) / Double(heardWords.count) >= 0.75
    }

    private func commandPayload(fromInterruption heard: String) -> String {
        var text = heard.trimmingCharacters(in: .whitespacesAndNewlines)

        if let range = text.range(of: "jarvis", options: [.caseInsensitive, .diacriticInsensitive]) {
            return text[range.upperBound...]
                .trimmingCharacters(in: CharacterSet.whitespacesAndNewlines.union(.punctuationCharacters))
        }

        let lower = text.lowercased()
        let yieldOnly = ["stop", "wait", "hold on", "hang on"]
        if yieldOnly.contains(lower.trimmingCharacters(in: .punctuationCharacters)) {
            return ""
        }

        for prefix in ["wait ", "hold on ", "hang on "] {
            if lower.hasPrefix(prefix) {
                text = String(text.dropFirst(prefix.count))
                    .trimmingCharacters(in: CharacterSet.whitespacesAndNewlines.union(.punctuationCharacters))
                break
            }
        }
        return text
    }

    private static func normalizedWords(_ text: String) -> [String] {
        text.lowercased()
            .components(separatedBy: CharacterSet.alphanumerics.inverted)
            .filter { !$0.isEmpty }
    }

    private func beginBargeInFinalize() {
        isSpeaking = false
        if bargeInFinalizeTask == nil {
            bargeInFinalizeTask = Task { [weak self] in
                guard let self else { return }
                await self.finishBargeInAfterUserPauses()
            }
        }
    }

    private func finishBargeInAfterUserPauses() async {
        let started = Date()
        while !Task.isCancelled {
            let now = Date()
            let quietFor = now.timeIntervalSince(lastBargeInTranscriptChange)
            if quietFor >= 0.9 || now.timeIntervalSince(started) >= 4.0 {
                break
            }
            try? await Task.sleep(for: .milliseconds(80))
        }

        if !latestBargeInTranscript.isEmpty {
            BargeInBuffer.store(commandPayload(fromInterruption: latestBargeInTranscript))
        }
        bargeInFinalizeTask = nil
        finalizeCurrentOutput()
    }

    private func stopBargeInListening() {
        if bargeInAudioEngine.isRunning {
            bargeInAudioEngine.stop()
        }
        if bargeInTapInstalled {
            bargeInAudioEngine.inputNode.removeTap(onBus: 0)
            bargeInTapInstalled = false
        }
        bargeInRequest?.endAudio()
        bargeInRequest = nil
        bargeInTask?.cancel()
        bargeInTask = nil
    }

    func speechSynthesizer(_ synthesizer: AVSpeechSynthesizer, didFinish utterance: AVSpeechUtterance) {
        finishSpeechOutput(utterance)
    }

    func speechSynthesizer(_ synthesizer: AVSpeechSynthesizer, didCancel utterance: AVSpeechUtterance) {
        finishSpeechOutput(utterance)
    }

    private func finishSpeechOutput(_ utterance: AVSpeechUtterance) {
        guard currentUtterance === utterance else { return }
        if didBargeIn {
            beginBargeInFinalize()
            return
        }
        finalizeCurrentOutput()
    }

    nonisolated func audioPlayerDidFinishPlaying(_ player: AVAudioPlayer, successfully flag: Bool) {
        Task { @MainActor [weak self] in
            guard let self, self.audioPlayer === player else { return }
            if self.didBargeIn {
                self.beginBargeInFinalize()
            } else {
                self.finalizeCurrentOutput()
            }
        }
    }

    private func finalizeCurrentOutput() {
        stopBargeInListening()
        currentUtterance = nil
        audioPlayer?.delegate = nil
        audioPlayer = nil
        isSpeaking = false
        spokenTextForEchoFilter = ""
        latestBargeInTranscript = ""
        let pending = completion
        completion = nil
        pending?.resume()
        audioRouteManager.refresh()
    }
}
