from __future__ import annotations

import argparse
import json
from typing import Any


def _drain_links() -> dict[str, Any]:
    from jarvis_mrb.world_linker import refresh_links

    totals = {"processed_events": 0, "linked_mentions": 0, "relation_evidence_added": 0, "explicit_projects_created": 0}
    last_event_id = 0
    for _ in range(50):
        batch = refresh_links(limit=5000)
        for key in totals:
            totals[key] += int(batch.get(key, 0))
        last_event_id = int(batch.get("last_event_id") or last_event_id)
        if int(batch.get("processed_events") or 0) < 5000:
            return {**totals, "last_event_id": last_event_id, "drained": True}
    raise RuntimeError("World linker still has work after 250,000 migration events; refusing to claim preparation is complete.")


def _drain_terms() -> dict[str, Any]:
    from jarvis_mrb.world_terms import refresh

    totals = {"processed_events": 0, "observations_added": 0, "conflicts_added": 0}
    generated: list[int] = []
    last_event_id = 0
    for _ in range(50):
        batch = refresh(limit=10_000)
        for key in totals:
            totals[key] += int(batch.get(key, 0))
        generated.extend(int(value) for value in batch.get("generated_event_ids") or [])
        last_event_id = int(batch.get("last_event_id") or last_event_id)
        if int(batch.get("processed_events") or 0) < 10_000:
            return {
                **totals,
                "generated_event_ids": generated,
                "last_event_id": last_event_id,
                "drained": True,
            }
    raise RuntimeError("Project-term reconciliation still has work after 500,000 events; refusing to claim preparation is complete.")


def _drain_document_versions() -> dict[str, Any]:
    from jarvis_mrb.world_document_versions import refresh

    totals = {
        "pairs_compared": 0,
        "pairs_with_changes": 0,
        "numeric_change_passages": 0,
        "lineage_candidates_rejected": 0,
    }
    generated: list[int] = []
    families = 0
    for _ in range(50):
        batch = refresh(limit_pairs=200)
        families = max(families, int(batch.get("families") or 0))
        for key in totals:
            totals[key] += int(batch.get(key, 0))
        generated.extend(int(value) for value in batch.get("generated_event_ids") or [])
        if int(batch.get("pairs_compared") or 0) < 200:
            return {
                "families": families,
                **totals,
                "generated_event_ids": generated,
                "drained": True,
            }
    raise RuntimeError("Document-version analysis still has work after 10,000 pairs; refusing to claim preparation is complete.")


def prepare(*, backup: bool = True, force_backfill: bool = False) -> dict[str, Any]:
    """Run the one-time deployment preparation sequence in a deterministic order."""
    from jarvis_mrb.world_migrations import run_migrations

    result: dict[str, Any] = {
        "ok": True,
        "migrations": {},
        "backfill": {},
        "extended_backfill": {},
        "refresh": {},
        "agency": {},
        "diagnostics": {},
        "errors": [],
    }

    result["migrations"] = run_migrations(backup=backup)

    from jarvis_mrb.world_backfill import backfill_existing_state
    from jarvis_mrb.world_extended_backfill import backfill_extended_state

    result["backfill"] = backfill_existing_state(force=force_backfill)
    result["extended_backfill"] = backfill_extended_state(force=force_backfill)
    if not bool(result["backfill"].get("ok", True)):
        result["ok"] = False
        result["errors"].extend(str(item) for item in result["backfill"].get("errors", []))
    if not bool(result["extended_backfill"].get("ok", True)):
        result["ok"] = False
        result["errors"].extend(str(item) for item in result["extended_backfill"].get("errors", []))

    # Drain bounded incremental processors rather than running each once and silently
    # leaving a large historical deployment partially linked/indexed.
    refresh_steps = (
        ("links", _drain_links),
        ("terms", _drain_terms),
        ("document_versions", _drain_document_versions),
    )
    for label, function in refresh_steps:
        try:
            result["refresh"][label] = function()
        except Exception as exc:
            result["ok"] = False
            result["refresh"][label] = {"error": str(exc)[:1000]}
            result["errors"].append(f"{label}: {exc}")

    # Events generated by term/document analysis must themselves enter the graph before
    # current intentions and Executive decisions are materialized.
    try:
        result["refresh"]["generated_event_links"] = _drain_links()
    except Exception as exc:
        result["ok"] = False
        result["refresh"]["generated_event_links"] = {"error": str(exc)[:1000]}
        result["errors"].append(f"generated_event_links: {exc}")

    for label, module_name, function_name in (
        ("intentions", "jarvis_mrb.world_executive", "refresh_intentions"),
        ("executive_loop", "jarvis_mrb.world_executive_loop", "refresh"),
    ):
        try:
            module = __import__(module_name, fromlist=[function_name])
            result["refresh"][label] = getattr(module, function_name)()
        except Exception as exc:
            result["ok"] = False
            result["refresh"][label] = {"error": str(exc)[:1000]}
            result["errors"].append(f"{label}: {exc}")

    try:
        from jarvis_mrb.agency_bootstrap import prepare as prepare_agency
        result["agency"] = prepare_agency(sync_goals=True)
        if not bool(result["agency"].get("ok")):
            result["ok"] = False
            result["errors"].extend(str(item) for item in result["agency"].get("errors", []))
    except Exception as exc:
        result["ok"] = False
        result["agency"] = {"ok": False, "error": str(exc)[:1000]}
        result["errors"].append(f"agency: {exc}")

    try:
        from jarvis_mrb.world_diagnostics import validate
        result["diagnostics"] = validate()
        if not bool(result["diagnostics"].get("ok")):
            result["ok"] = False
            result["errors"].extend(str(item) for item in result["diagnostics"].get("problems", []))
    except Exception as exc:
        result["ok"] = False
        result["diagnostics"] = {"error": str(exc)[:1000]}
        result["errors"].append(f"diagnostics: {exc}")

    return result


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Prepare a Jarvis installation after pulling a world-model upgrade."
    )
    parser.add_argument("--no-backup", action="store_true", help="Skip the pre-upgrade world SQLite backup.")
    parser.add_argument(
        "--force-backfill",
        action="store_true",
        help="Replay historical source stores even if their one-time completion sentinels exist.",
    )
    args = parser.parse_args()
    result = prepare(backup=not args.no_backup, force_backfill=args.force_backfill)
    print(json.dumps(result, indent=2, sort_keys=True, ensure_ascii=False, default=str))
    raise SystemExit(0 if bool(result.get("ok")) else 1)


if __name__ == "__main__":
    main()
